version: '3'

services:
  mysql:
    build:
      context: ./docker/mysqlwp
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysqlwp
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always

  php:
    build:
      context: ./docker/phpwp
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-phpwp
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./wp:/var/www/html
    links:
      - mysql