version: '3'

services:
  mysql:
    build:
      context: ./vendor/docker/mysqlwp
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysqlwp
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"

  wpcli:
    image: wordpress:cli
    volumes:
      - ./vendor/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    depends_on:
      - mysql


  php:
    build:
      context: ./vendor/docker/phpwp
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-phpwp
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./vendor/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    links:
      - mysql
volumes:
  db_data: